
<!--Common footer -->				
			<div class="bottom">
			
					<p>CSC 174 Advance Front End Development, Project One</p>
						
					<p>One Man Army Team members: Jack Zhang, Isaac Mosebrook, Tara Anacker, Stephanie Pollocks</p>
						
					<p>For more information about the team, please see the <a class="c-link" href="colophon.php">Colophon</a></p>
			</div>

		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
    </body>
</html>
